#Build container from github package
services:
  server:
    container_name: disaster_eater
    image: ghcr.io/echelon35/disastereater:latest
    env_file:
      - ./.env.prod
    environment:
      NODE_ENV: production
    ports:
      - 4001:4001