name: Deploy Docker Container

on:
  push:
    branches:
      - main  # Déclencher le workflow lorsqu'un push est fait sur la branche "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # 3. Log in to GitHub Docker registry (GitHub Packages)
    - name: Log in to GitHub Docker Registry
      run: echo "${{ secrets.GDR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    # 4. Build the Docker image
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/disastreameater:latest .

    # 5. Push Docker image to GitHub Packages
    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/disastreameater:latest

    # 6. Deploy to server via SSH
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_URL }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 600s
        script: |
          cd /opt/disastreamapi
          echo "${{ secrets.GDR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/${{ github.repository_owner }}/disastreameater:latest
          docker compose up -d
